- name: Start web app container
  docker_container:
    name: hines-site
    image: hines-site
    recreate: yes
    restart_policy: always
    state: started
    ports:
        - "443:443"

- name: Start api container
  docker_container:
    name: flask_api
    image: flask_api
    recreate: yes
    restart_policy: always
    state: started
    ports:
        - "2000:2000"