- name: Build & run Bill Tracker and Flask api
  hosts: localhost
  become: yes
  
  tasks:
    - name: Build web app & api container
      import_role:
        name: build

    - name: Stop & remove old containers
      import_role:
        name: teardown

    - name: Spin up web app and api
      import_role:
        name: deploy